# Generated by Django 4.1.5 on 2023-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.TextField(default="default"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(default="https://www.default.com/", max_length=255),
        ),
    ]
