# Generated by Django 4.1.5 on 2023-01-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("Hard", "Hard"), ("Soft", "Soft")],
                default="Hard",
                max_length=4,
            ),
        ),
    ]
