# Generated by Django 4.1.5 on 2023-01-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="expected_return",
            new_name="expected_return_date",
        ),
        migrations.RemoveField(
            model_name="borrowing",
            name="actual_return",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
