# Generated by Django 4.1.5 on 2023-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "borrowing",
            "0002_rename_expected_return_borrowing_expected_return_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(),
        ),
    ]
