# Generated by Django 4.1.5 on 2023-01-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0004_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(),
        ),
    ]
