# Generated by Django 4.1.5 on 2023-02-06 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0006_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
