# Generated by Django 4.1.5 on 2023-02-08 10:20

import borrowing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0007_rename_book_id_borrowing_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(
                blank=True, default=borrowing.models.get_return_date
            ),
        ),
    ]
